[build]
  base = "Frontend" # Especifica el directorio base, en tu caso 'Frontend'.
  publish = "Frontend/public" # Especifica la carpeta pública con los archivos estáticos.

[[redirects]]
from = "/api/*"
to = "https://nombre-del-backend.vercel.app/api/:splat"
status = 200
